### ISSUE TITLE
Raumplan - Elemente/IDs normalisieren

### ISSUE THREAD

**Issue by alexplusde** [MitchiLaser/Features_Elly_Website#4]
die Fläche eines Raumes soll beim Hovern hervorgehoben werden. Entsprechend benötigt ein Raum eine eindeutige und über CSS gut ansteuerbare ID. Ich habe das in einem ähnlichen Projekt schon mal umgesetzt. 

```
    g[id^=e1].highlight [id^=room] {
        fill: rgb(189, 5, 124) !important;
    }    
    g[id^=e1]:hover [id^=room] {
        fill: rgb(28,90,129) !important;
    }
    g[id^=segment]:hover * {
        cursor: pointer;
    }
```

Mit `<g>`-Elementen (Ebenen / Pfad-Gruppen) ist man da relativ flexibel, egal, ob darunter ein `<path>` liegt, ein `<circle />` oder sonst etwas. 

Die Affinity-Datei habe ich noch, da lässt sich der Export 1:1 nutzen. Ich kann die hier nochmal ins Repository laden.

**Comment by MitchiLaser** [comment]
Alle Räume haben in den neu erstellten SVGs ihre eigene ID bekommen. Diese besteht aus der Raumnummer (aofern der Raum eine Nummer hat) und gegebenenfalls auch dem Raumnamen. Die Fluchtwege wurden zu einer Gruppe zusammengefügt, die ihre eigene ID hat. Dadurch ist es dann möglich, einen Button (oder ähnliches) namens "Fluchtwege anzeigen" in die Webseite einzubauen.

**Comment by MitchiLaser** [comment]
Die SVG Dateien wurden weitestgehend normalisiert und zu einer Datei mit mehreren Ebenen zusammengeführt. Eine einfache Ansteuerungsmöglichkeit, um die SVG Dateien zu kontrollieren, wird gerade in dem Ordner "Stand alone Web App" entwickelt.
