### ISSUE TITLE
Backend: Module: Bootstrap3-Fragmente nutzen

### ISSUE THREAD

**Issue by alexplusde** [MitchiLaser/Features_Elly_Website#5]
In REDAXO werden sog. Fragmente benutzt, um kleine HTML- oder PHP-Templates zu befüllen. 
https://redaxo.org/doku/master/fragmente

Man könnte diese nutzen, um die Darstellung von Inhalten im Backend schöner zu machen und dabei auf bootstrap3-Klassen setzen, die im Backend zur Verfügung stehen.

**Comment by MitchiLaser** [comment]
Hört sich vielversprechend an. Da muss ich mich aber erst einmal einlesen.
